### ISSUE TITLE
Need a volume to upload/download files (images to glance)

### ISSUE THREAD

**Issue by GillesMocellin** [ullbergm/docker-openstack-client#1]
Hello,
Thank you for you work.
I'm using your container, but have trouble.
I was downloading an image with `openstack image save --file file.img image`
And I didn't see any file created.
After I while I understand that the file was created inside the container.
I should mount a volume from my current dir, but to what dir inside the container ?

**Comment by ullbergm** [comment]
best thing would probably be to mount a volume (-v /data:/data) and then specify the full path where you want the image to be saved (--file /data/file.img).

I haven't tried it but it should work.

**Comment by GillesMocellin** [comment]
Yes, that's what I finaly do, thanks !
